CREATE TABLE STUDENTS (
  ST_ID SERIAL PRIMARY KEY,
  ST_NAME VARCHAR(20),
  ST_LAST VARCHAR(20)
);

SELECT * FROM STUDENTS;
-- Import data into STUDENTS from a text file
COPY STUDENTS(ST_ID, ST_NAME, ST_LAST) FROM '/Users/fuadfatali/Desktop/Fuad_Fataliyev_13537_POM1/students.txt' WITH DELIMITER ' ';

CREATE TABLE INTERESTS (
  STUDENT_ID INT REFERENCES STUDENTS(ST_ID),
  INTEREST VARCHAR(20)
);

COPY INTERESTS(STUDENT_ID, INTEREST) FROM '/Users/fuadfatali/Desktop/Fuad_Fataliyev_13537_POM1/interests.txt' WITH DELIMITER ' ';


SELECT * FROM INTERESTS;
