BEGIN;

-- Rename the STUDENTS.ST_ID to STUDENTS.STUDENT_ID
ALTER TABLE STUDENTS RENAME COLUMN ST_ID TO STUDENT_ID;

-- Change the length of STUDENTS.ST_NAME and STUDENTS.ST_LAST from 20 to 30
ALTER TABLE STUDENTS
  ALTER COLUMN ST_NAME TYPE VARCHAR(30),
  ALTER COLUMN ST_LAST TYPE VARCHAR(30);

-- First, create a new table to hold the array data
CREATE TABLE NEW_INTERESTS (
  STUDENT_ID INT,
  INTERESTS TEXT[]
);

-- Populate the NEW_INTERESTS table with array_agg of interests grouped by STUDENT_ID
INSERT INTO NEW_INTERESTS (STUDENT_ID, INTERESTS)
SELECT STUDENT_ID, array_agg(INTEREST ORDER BY INTEREST) FROM INTERESTS GROUP BY STUDENT_ID ORDER BY STUDENT_ID;

-- Drop the old INTERESTS table
DROP TABLE INTERESTS;

-- Rename the NEW_INTERESTS table to INTERESTS
ALTER TABLE NEW_INTERESTS RENAME TO INTERESTS;

-- Add the foreign key constraint to the new INTERESTS table
ALTER TABLE INTERESTS ADD CONSTRAINT fk_student FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID);

SELECT * FROM INTERESTS;

COMMIT;
