BEGIN;

-- Renaming column STUDENT_ID back to ST_ID in STUDENTS table
ALTER TABLE STUDENTS RENAME COLUMN STUDENT_ID TO ST_ID;

-- Altering column types for ST_NAME and ST_LAST back to VARCHAR(20) in STUDENTS table
ALTER TABLE STUDENTS
  ALTER COLUMN ST_NAME TYPE VARCHAR(20),
  ALTER COLUMN ST_LAST TYPE VARCHAR(20);

-- Recreating the old INTERESTS table structure
CREATE TABLE OLD_INTERESTS (
  STUDENT_ID INT,
  INTEREST VARCHAR(20)
);

-- Inserting interests back into the old table structure
INSERT INTO OLD_INTERESTS (STUDENT_ID, INTEREST)
SELECT STUDENT_ID, UNNEST(INTERESTS)
FROM INTERESTS;

-- Dropping the new INTERESTS table
DROP TABLE INTERESTS;

-- Renaming OLD_INTERESTS back to INTERESTS
ALTER TABLE OLD_INTERESTS RENAME TO INTERESTS;

SELECT * FROM INTERESTS;

COMMIT;

